[[shards]]
name = "shard1"
idx = 0
address = "127.0.0.1:8080"
replicas = ["127.0.0.11:8080"]

[[shards]]
name = "shard2"
idx = 1
address = "127.0.0.2:8080"
replicas = ["127.0.0.22:8080"]

[[shards]]
name = "shard3"
idx = 2
address = "127.0.0.3:8080"
replicas = ["127.0.0.33:8080"]

[[shards]]
name = "shard4"
idx = 3
address = "127.0.0.4:8080"
replicas = ["127.0.0.44:8080"]